version: '3.7'

services:
  db:
    container_name: 'student-assistant'
    image: mysql
    restart: always
    ports:
      - 3305:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5000:8080

  db2:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_USER: user
      MYSQL_HOST: localhost
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: shadow
    ports:
      - '3308:3306'

volumes:
  dbdata:
